import Link from "next/link";

export const metadata = {
  title: "Terms of Service — Sky Style",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen px-6 py-16 max-w-2xl mx-auto" style={{ background: "var(--background)" }}>
      <Link href="/" className="text-sm mb-8 inline-block hover:opacity-70" style={{ color: "var(--accent)" }}>
        ← Back to Sky Style
      </Link>

      <h1 className="text-3xl font-bold mb-2" style={{ color: "var(--foreground)" }}>
        Terms of Service
      </h1>
      <p className="text-sm mb-8" style={{ color: "var(--foreground)", opacity: 0.5 }}>
        Last updated: February 2026
      </p>

      <div className="space-y-6 text-sm leading-relaxed" style={{ color: "var(--foreground)", opacity: 0.8 }}>
        <section>
          <h2 className="text-lg font-semibold mb-2" style={{ opacity: 1 }}>Plain language first</h2>
          <p>
            We follow{" "}
            <a
              href="https://github.com/COOLmanYT/people-first-design"
              target="_blank"
              rel="noopener noreferrer"
              className="underline"
              style={{ color: "var(--accent)" }}
            >
              People First Design
            </a>{" "}
            principles. That means these terms are written in clear, everyday language — no
            lawyer soup. If something is unclear, please{" "}
            <a
              href="https://github.com/COOLmanYT/what2wear/issues"
              target="_blank"
              rel="noopener noreferrer"
              className="underline"
              style={{ color: "var(--accent)" }}
            >
              open an issue
            </a>{" "}
            and we will fix it.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-2" style={{ opacity: 1 }}>What Sky Style does</h2>
          <p>
            Sky Style fetches real-time weather data from multiple public sources and uses AI
            to recommend what you should wear. It is a helpful tool, not a professional
            meteorological or fashion service.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-2" style={{ opacity: 1 }}>Your account</h2>
          <p>
            You sign in with GitHub or Google. We store your user ID, name, email, and profile
            image so you can log in again. We do not create a separate password for you.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-2" style={{ opacity: 1 }}>Free and Pro plans</h2>
          <p>
            Free accounts have daily limits (5 AI uses, 10 follow-ups, 1 closet use, 1 source
            pick per day). Pro accounts get higher limits, more features, and weekly credits.
            Pro pricing is listed on the homepage and may change with 30 days notice.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-2" style={{ opacity: 1 }}>Bring Your Own Key</h2>
          <p>
            Pro users can provide their own AI API key for requests. This key is used only for
            that single request and is <strong>never stored</strong> on our servers. You are
            responsible for any charges from your API provider.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-2" style={{ opacity: 1 }}>No dark patterns</h2>
          <p>
            We do not use guilt buttons, fake urgency, confusing opt-outs, or tricks of any
            kind. If you want to stop using Sky Style, simply stop. Your data can be deleted on
            request.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-2" style={{ opacity: 1 }}>Accuracy disclaimer</h2>
          <p>
            Weather data comes from third-party sources (OpenWeatherMap, Open-Meteo, Bureau of
            Meteorology). AI recommendations are generated by language models. Neither the
            weather data nor the outfit suggestions are guaranteed to be accurate. Use your own
            judgement.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-2" style={{ opacity: 1 }}>Availability</h2>
          <p>
            We do our best to keep the service running, but outages happen. We are not liable
            for downtime, data loss, or any damages arising from use of the service.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-2" style={{ opacity: 1 }}>Your responsibilities</h2>
          <ul className="list-disc pl-5 space-y-1">
            <li>Do not abuse the service or circumvent rate limits.</li>
            <li>Do not use the service for any unlawful purpose.</li>
            <li>Keep your account credentials (OAuth tokens) secure.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-2" style={{ opacity: 1 }}>Changes to these terms</h2>
          <p>
            If we change these terms, we will update this page and the &quot;last updated&quot; date.
            For material changes, we will try to notify users through the dashboard.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-2" style={{ opacity: 1 }}>Open source</h2>
          <p>
            Sky Style is open source. You can view the full source code at{" "}
            <a
              href="https://github.com/COOLmanYT/what2wear"
              target="_blank"
              rel="noopener noreferrer"
              className="underline"
              style={{ color: "var(--accent)" }}
            >
              github.com/COOLmanYT/what2wear
            </a>
            .
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-2" style={{ opacity: 1 }}>Contact</h2>
          <p>
            Questions? Open an issue on{" "}
            <a
              href="https://github.com/COOLmanYT/what2wear/issues"
              target="_blank"
              rel="noopener noreferrer"
              className="underline"
              style={{ color: "var(--accent)" }}
            >
              GitHub
            </a>
            .
          </p>
        </section>
      </div>
    </div>
  );
}
